import "styles/globals.css";
import localFont from "next/font/local";
import Head from "next/head";
import { Provider } from "react-redux";
import store from "../store";

export const proxima = localFont({
  src: [
    {
      path: "../../public/font/ProximaNova-Bold.ttf",
      weight: "700",
    },
    {
      path: "../../public/font/ProximaNova-Light.ttf",
      weight: "300",
    },
  ],
  variable: "--proxima-font",
});

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Star Company</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Provider store={store}>
        <Component {...pageProps} />
      </Provider>
    </>
  );
}
